# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('5', '5 - The best!'), ('4', '4 - Delicious!'), ('3', '3 - Okay'), ('2', '2 - Subpar'), ('1', '1 - A no from me')], default=5, max_length=1),
        ),
    ]
